# fly.toml app configuration file generated for tfl-travel-time-backend-polished-log-1447 on 2024-01-28T16:33:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tfl-travel-time-backend-polished-log-1447'
primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
    PORT = '3001'

[[services]]
    protocol = "tcp"
    internal_port = 3001

[http_service]
    internal_port = 3001
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 1
    processes = ['app']

[[services.ports]]
    handlers = ['http']
    port = 80

[[services.ports]]
    handlers = ['tls', 'http']
    port = 443

[services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
